//VARIE 

//GAMELOOP
void gameloop () {
	while() {
	
	//ROBA IN ESECUZIONE DURANTE IL GIOCO
	
	//BREAK DOVUTO ALLA PRESSIONE DI UN esc?
	
	}
	
// MATRICE COME SCHERMO!!!

// COME FARE UNA MATRICE CON LE MISME PROPORZIONI DELLO SCHERMO, IN ULTIMO RIDIMENSIONARE OPPORTUNAMENTE